### ISSUE TITLE
Detection code

### ISSUE THREAD

**Issue by prsbsvrn** [qhfan/RMT#15]
Hi thanks for the codes,
When detection code will be realized?

**Comment by qjt-1122** [comment]
Hi thanks for the codes,
When Semantic Segmentation code will be realized?

**Comment by prsbsvrn** [comment]
Hi, thanks for your updates. Is there any specific code for object detection? Will it be uploaded?

**Comment by qhfan** [comment]
It will be uploaded within taday

**Comment by qhfan** [comment]
Thank you for your attention, I will try to uploaded them within today

**Comment by prsbsvrn** [comment]
thank you and in another issue, there is a request for rmt.py as backbone. Can you upload this code please?

**Comment by qhfan** [comment]
The codes for detection are uploaded, you can refer RMT.py in the mmdet/models/backbones
