### ISSUE TITLE
Can you share the pre-training weights or how long does it take to train your model 

### ISSUE THREAD

**Issue by ouusan** [qhfan/RMT#16]
Hello. Thank you for your work! 
Can you share the pre-trained weights?
or i want to ask how long does it take to train your model on the imagenet dataset for each size?

**Comment by qhfan** [comment]
We will release the pretrained models after we finish reorgnizing them.
For small model (27M), we use 32 V100 to train it for about 1.5days on ImageNet.

**Comment by ouusan** [comment]
Thanks for your reply ! 
you mean 32 GPUs or is it a 32G V100?(It is impossible for me if 32 GPUs....)
I'm trying to apply your rmt structure to my own task, but the results are much worse because original task uses pretrained weights, I'm very looking forward to your update on the pre-trained weights! (Sorry to bother you again, around what month will it be?)
Thank you! ! !

**Comment by qhfan** [comment]
Thanks for your attention to our work. The pretrained weights have been updated.
