### ISSUE TITLE
could you please offer us your environment informations?

### ISSUE THREAD

**Issue by lyqqhgzj** [qhfan/RMT#22]
you can just use the following commands
1.`pip install pipreqs -i https://pypi.doubanio.com/simple` or `pip install pipreqs -i https://pypi.tuna.tsinghua.edu.cn/simple/`
2. `pipreqs .`
3. then you can get `requirements.txt`, easy?
thank you very much :)

**Comment by qhfan** [comment]
We have updated the install.sh
